version: '3'
services:
  # The Application setup php
  php:
    container_name: php
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    networks:
      - app-network
  # The Web Server
  nginx:
    container_name: nginx
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    volumes:
      - ./:/var/www/html
    working_dir: /var/www/html
    ports:
      - 80:80
    networks:
      - app-network
  # MySQL Service
  mysql:
    container_name: mysql
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
    - MYSQL_DATABASE=laravel
    - MYSQL_ROOT_PASSWORD=root
    - MYSQL_USER=root
    - MYSQL_PASSWORD=root
    volumes:
      - ./docker/mysql/dbdata:/var/lib/mysql
    networks:
      - app-network
  # Nodejs
  node:
    container_name: node
    build:
      context: .
      dockerfile: docker/nodejs/Dockerfile
    networks: 
      - app-network

#Docker Networks
networks:
  app-network:
    driver: bridge
